-- Harden the helper / trigger functions to satisfy Supabase's database
-- linter advisors. None of these functions are intended to be called as
-- RPCs — they only run from triggers — so we revoke EXECUTE from the
-- web-facing roles and pin the search_path on the non-DEFINER one.

-- Fix function_search_path_mutable
ALTER FUNCTION public.touch_updated_at() SET search_path = public;

-- Fix anon_security_definer_function_executable +
-- authenticated_security_definer_function_executable for handle_new_user.
-- Trigger fires via auth schema; PostgREST RPC is not the intended path.
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;

-- Same for rls_auto_enable (auto-generated by Supabase when "Enable
-- automatic RLS" was selected at project creation).
REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM PUBLIC, anon, authenticated;
